[versions]
agp = "8.13.0"
kotlin = "2.2.20"

[libraries]
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version = "0.29.0" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.8.0" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
runner = { module = "androidx.test:runner", version = "1.7.0" }
sha1 = { module = "org.kotlincrypto.hash:sha1", version = "0.7.1"  }
uri-kmp = { module = "com.eygraber:uri-kmp", version = "0.0.20" }
nott = { module = "io.github.remmerw:nott", version ="0.1.6" }
buri = { module = "io.github.remmerw:buri", version = "0.0.3" }
grid = { module = "io.github.remmerw:grid", version = "0.1.2" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
